DEBUG = True

DB_HOST = "192.168.99.100"
DB_PORT = 5432
DB_USER = 'victorsimao'
DB_PASSWORD = 'padawan'
DB_DATABASE = 'postgres'
SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_DATABASE}'
SQLALCHEMY_TRACK_MODIFICATIONS = True
JWT_SECRET_KEY = 'LeroyJenkins'
