"""empty message

Revision ID: c8bf76a11964
Revises: ea549145846c
Create Date: 2020-05-29 18:51:22.291614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bf76a11964'
down_revision = 'ea549145846c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hoteis', 'cidade',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('hoteis', 'nome',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hoteis', 'nome',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('hoteis', 'cidade',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
