"""empty message

Revision ID: ea549145846c
Revises: 
Create Date: 2020-05-29 18:37:29.377830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea549145846c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoteis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('estrelas', sa.Integer(), nullable=True),
    sa.Column('diaria', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoteis')
    # ### end Alembic commands ###
